### ISSUE TITLE
No syntax highlighting for comment (simple or block) in arrays

### ISSUE THREAD

**Issue by kenkouot** [HerringtonDarkholme/yats.vim#1]
![image](https://cloud.githubusercontent.com/assets/2964310/9896211/a878b2ce-5bed-11e5-9ee9-266a99398946.png)

**Comment by HerringtonDarkholme** [comment]
Thanks for reporting!
Fixed in https://github.com/HerringtonDarkholme/yats.vim/commit/1bc9e782251614ab928f34d2e61bff58bbc94817
