### ISSUE TITLE
public, static, and private keywords appear as errors if class extends two lines

### ISSUE THREAD

**Issue by indiesquidge** [HerringtonDarkholme/yats.vim#10]
<img width="655" alt="screen shot 2016-06-21 at 5 22 31 pm" src="https://cloud.githubusercontent.com/assets/3409645/16250771/f9a10782-37d4-11e6-990b-9ffa499ac137.png">
Notice the open curly brace for the `class` is now on line `108`
<img width="658" alt="screen shot 2016-06-21 at 5 22 56 pm" src="https://cloud.githubusercontent.com/assets/3409645/16250772/f9a2b38e-37d4-11e6-9074-4b4472e8b340.png">

The reason this is a problem is not because I want a curly brace on it's own line. It is because sometimes the class definition is too long for one line

<img width="714" alt="screen shot 2016-06-21 at 5 19 12 pm" src="https://cloud.githubusercontent.com/assets/3409645/16250798/3a016d30-37d5-11e6-870a-ff8d9befc8c7.png">

Notice how all highlighting on line `108` is also gone.

**Comment by indiesquidge** [comment]
Just going off of the commit message, perhaps this was attempted to be fixed in: https://github.com/HerringtonDarkholme/yats.vim/commit/d1bfa9621f54ddef42b0225492ce18c0bb78dec3?

**Comment by HerringtonDarkholme** [comment]
Thanks for reporting! I'm trying to fix it.

**Comment by HerringtonDarkholme** [comment]
Fixed in https://github.com/HerringtonDarkholme/yats.vim/commit/6cc20675649e411bc9adb414341176c9ee845ce5
