### ISSUE TITLE
Syntax highlighting breaks insude of objects / arrow functions

### ISSUE THREAD

**Issue by tylucaskelley** [HerringtonDarkholme/yats.vim#101]
Haven't narrowed down what the exact cause is yet, but it appears that functions inside of an object break syntax highlighting:

![image](https://user-images.githubusercontent.com/5448759/53932218-9577a980-4066-11e9-88b9-e62f5ed92e89.png)

**Comment by tylucaskelley** [comment]
Note the lack of highlighting for `let` and the inline comment

**Comment by HerringtonDarkholme** [comment]
Can you disable other plugins and try it with a minimal vimrc? I guess this is something related to #100

**Comment by tylucaskelley** [comment]
Yeah will do

**Comment by HerringtonDarkholme** [comment]
Probably something conflicts.
https://github.com/HerringtonDarkholme/yats.vim/issues/100#issuecomment-473001151
