### ISSUE TITLE
Support new readonly shorthand in typescript 3.4

### ISSUE THREAD

**Issue by dsifford** [HerringtonDarkholme/yats.vim#102]
Example of issue:

```ts
  let list1: number[] = [];
  let list2: readonly number[] = [];
  //         ^^^^^^^^ ^^^^^^
```
I tried to take a quick stab at this but it appears that it's going to take a somewhat significant effort to squeeze this in. 

More info here: https://devblogs.microsoft.com/typescript/announcing-typescript-3-4-rc/

**Comment by HerringtonDarkholme** [comment]
Thanks for the information! I'll update it soon!

**Comment by HerringtonDarkholme** [comment]
Fixed!
