### ISSUE TITLE
some problems with ctag generation

### ISSUE THREAD

**Issue by wachri** [HerringtonDarkholme/yats.vim#103]
There are some cases where the ctag generation not working correctly:

### readonly
```
class Greeter {
    private readonly greeting: string;
}
```
you get `readonly : members` displayed instead of `greeting: member`

### doubled entries
```
class Test {
    private testPrivate(): void {}
}
```
results in
```
  Test : classes

  Test : classes

  testPrivate : members

 -testPrivate : members  
```

### Multiple interfaces
```
class Test implements Test, Test2 {
    aPublicMethod(): void {}
    private testPrivate(): void {}
}
```

results in
```
  Test : classes

  Test : classes

  testPrivate : members
```

The public methods aren't listed

**Comment by HerringtonDarkholme** [comment]
Ctags is just some regex. Public method without access modifier cannot be distinguished from others.
