### ISSUE TITLE
Support async object property methods

### ISSUE THREAD

**Issue by dsifford** [HerringtonDarkholme/yats.vim#108]
Just writing this here so that it's being tracked. I might attempt to take a stab at this if time allows one of these days....

Here's a small example of what's broken...

```ts
const foobar = {
    async foo() {
//  ^^^^^
        return Promise.resolve('foo');
    },
    bar: 'bar',
}
```

Should be pretty self-explanatory.

**Comment by HerringtonDarkholme** [comment]
I think current highlighting is good enough. `async` is highlighted as keyword

**Comment by dsifford** [comment]
In the case I present, `async` is highlighted as `typescriptObjectLabel` which is linked to `keyword`.

In the theme that I maintain, I remove that link because object labels are not highlighted the same way as keywords. So it would be nice to have a specific group targeting the `async` there, or, mark it as explicitly `keyword`.

**Comment by HerringtonDarkholme** [comment]
Pull request is welcome.

**Comment by HerringtonDarkholme** [comment]
I have updated it!
