### ISSUE TITLE
Highlighting issue with styled components

### ISSUE THREAD

**Issue by JoosepAlviste** [HerringtonDarkholme/yats.vim#109]
Hey, I've encountered this weird bug quite often now. Have you encountered this before or know of a solution?

As shown in the screenshot below, all code after a styled components definition is highlighted as `typescriptTemplate`. This happens after modifying a file and scrolling down. 

![image](https://user-images.githubusercontent.com/9450943/57182208-3804ab00-6ea5-11e9-9c10-5bb49b54dfa5.png)

## How to reproduce

I managed to reproduce it quite often the following way:

1. Open the file I pasted below
2. Make sure that the file is a bit longer than the Vim screen (the `Egg` styled component definition should end below the viewport)
3. Scroll to the top of the file
4. Delete line 5 (`font-size: 1rem`)
5. Scroll to the bottom with `G`
6. Press F10 to see the syntax group (mapping from my vimrc below)

```jsx
import * as React from 'react'
import styled from 'styled-components'

const AnotherComponent = styled.div`
  font-size: 1rem;
`

const Egg = styled.h1`
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
  color: black;
`

const CoolComponent = () => (
  <Egg>This is a test thing</Egg>
)

export default CoolComponent
```

## Minimal vimrc

```vim
call plug#begin('~/.vim/plugged')

Plug 'HerringtonDarkholme/yats.vim'
Plug 'styled-components/vim-styled-components', { 'branch': 'main' }

call plug#end()

function! SynStack()
  if !exists("*synstack")
    return
  endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc

nnoremap <silent> <F10> :call SynStack()<CR>
```

**Comment by HerringtonDarkholme** [comment]
Actually this is vim feature. Vim will skip highlighting after several lines.

**Comment by JoosepAlviste** [comment]
Hmm, the problem doesn't happen when only YATS is installed but it does if styled-components is also installed. Also, the file is sonly 59 lines long so would Vim really skip highlighting in that case?

What's extra weird in that case is that `typescriptTemplate` syntax group gets applied (so it looks like syntax highlighting is actually applied, just that it's incorrect).

Anyways, did you manage to reproduce the issue?

**Comment by JoosepAlviste** [comment]
I also recorded a gif, maybe it's easier to understand the problem this way:

https://i.gyazo.com/36f63f7ecaaf2c28ac13b7e201e6807f.mp4

**Comment by tomaskallup** [comment]
@JoosepAlviste try to put `autocmd BufReadPost *.tsx,*.ts,*.jsx,*.js :syntax sync fromstart` in your vimrc and see if that solves the problem.

**Comment by JoosepAlviste** [comment]
@tomaskallup looks like this solves my problem, thanks!

I guess it's probably OK to keep it as a permanent solution since I don't have any super large `tsx` files.
