### ISSUE TITLE
Confusion with nested parens

### ISSUE THREAD

**Issue by mhartington** [HerringtonDarkholme/yats.vim#11]
Given the following class

```typescript
export class SearchPage {
  private form = this.formBuilder.group({
    'term': ['', Validators.required],
    'filter': ['everything']
  });
  constructor(
    private nav: NavController,
    public formBuilder: FormBuilder
  ) {
  }
  search() {
    this.nav.push(ResultsPage, {
      'search': this.form.value
    });
  }
}
```
It appears that this syntax will apply the syntax groups of `['typescriptClassBlock', 'typescriptMethodBlock', 'javaScriptBraces']`

This causes highlights to appear off.

<img width="1680" alt="screen shot 2016-09-07 at 8 39 30 pm" src="https://cloud.githubusercontent.com/assets/2835826/18333303/b97ae96c-753b-11e6-8478-fdf7675a364f.png">

Not  the off parens in `search()` 

The opening parens in `this.nav.push(ResultsPage, {` is marked as a `javaScriptBraces`, which causes highlighting problems.  I have yet to dig through the syntax files, but will try to put together a PR if I can find the cause.

Likely, not a huge issue, but still something to note.

Cheers!

**Comment by HerringtonDarkholme** [comment]
hmm... I have tested locally. The opening parens is marked as `typescriptClassBlock->typescriptMethodBlock->typescriptArgumentList->typescriptBraces` and the inner object is marked as `typescriptObjectLiteral`.

I suspect there are syntax highlighting in your configuration, probably introduced in https://github.com/HerringtonDarkholme/yats.vim/issues/9

**Comment by mhartington** [comment]
Ahh, indeed it is.Thanks!
