### ISSUE TITLE
Need a single-file version of typescript.vim

### ISSUE THREAD

**Issue by brammool** [HerringtonDarkholme/yats.vim#113]
The typescript.vim file contains:
`runtime syntax/common.vim`
That might be nice when installing this as a package, but it's not OK when I would include this in the Vim distribution. Not only does it load any "common" syntax laying around, it's also making it slow, since it has to search for files, open them, etc.

Could you make a single file version that could be included in the Vim distribution?
I assume the license is already OK, since it mentions using the Vim license.
Would be nice to have typescript support in Vim out of the box.

**Comment by HerringtonDarkholme** [comment]
Sure! I'm happy to do that and happy to see Vim can include TypeScript's syntax out of box!

I will provide a single version of typescript.vim in this repo. A pull request to vim's repo is also OK.

**Comment by brammool** [comment]
Thanks for the quick response!

> Sure! I'm happy to do that and happy to see Vim can include
> TypeScript's syntax out of box!
> 
> I will provide a single version of typescript.vim in this repo. A pull
> request to vim's repo is also OK.

Perhaps the indent file can also be done?  I expect it to be very
similar to Javascript, but probably still a bit different.

-- 
All good vision statements are created by groups of people with bloated
bladders who would rather be doing anything else.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Any progress on making a one-file syntax/typescript.vim ?

**Comment by brammool** [comment]
Since I'm editing typescript I needed the single file.  I added it to the Vim runtime.  Please make updates as needed.

**Comment by HerringtonDarkholme** [comment]
I'm so sorry I'm too busy with my day jobs. I'll try add a script to generate single file.

**Comment by HerringtonDarkholme** [comment]
I have added a merge scrip to the repo. The output file is named `merged.vim`

**Comment by brammool** [comment]
> I have added a merge scrip to the repo. The output file is named `merged.vim`

Thanks.  Can you also change the HiLink commands to "hi def link", like
has been done for all the syntax files in the distribution?

Also, you should set 'cpo', because line continuation is being used.
It's already in indent/typescript.vim but not in the syntax file.


-- 
Corduroy pillows: They're making headlines!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
