### ISSUE TITLE
support common test framework global API

### ISSUE THREAD

**Issue by crusoexia** [HerringtonDarkholme/yats.vim#117]
Nowadays dev spent half time to read/write/fix UTs, so it would be nice to have the common test apis highlighted.

current yats test file:
<img width="969" alt="Screen Shot 2019-06-05 at 11 02 57 PM" src="https://user-images.githubusercontent.com/5928754/58967118-22590d00-87e6-11e9-86bc-1bcfc3057e9b.png">

js file highlighted by `vim-javascript`:
<img width="815" alt="Screen Shot 2019-06-05 at 11 03 18 PM" src="https://user-images.githubusercontent.com/5928754/58967147-369d0a00-87e6-11e9-99b2-b2dd5a4dc98f.png">

These keyword are good highlight candidates:

```vim-script
describe it test before after beforeEach afterEach beforeAll afterAll expect assert
```

**Comment by crusoexia** [comment]
@HerringtonDarkholme Sorry I want to bring this back to table. These keywords are marked as `typescriptGlobal`, however, they are not part of typescript but apis provide by common test frameworks as `jest` `mocha` `chai` etc., could you give these keywords another identifier other than `typescriptGlobal`? How about `typescriptTestKeywords`? With different identifier colorschemes can set different color to the different things.

Thanks

**Comment by HerringtonDarkholme** [comment]
Pull request is welcome.

**Comment by crusoexia** [comment]
Created. Let me know if anything is not match the convention.
