### ISSUE TITLE
Differentiating Function Calls

### ISSUE THREAD

**Issue by iansinnott** [HerringtonDarkholme/yats.vim#12]
Hey, this is a great project. I was just wondering if I'm missing something or if this is an unsupported feature. I'd like a function call to be highlighted different than a function. I.e. `someFunc` would be highlighted as a variable and `someFunc()` would be highlighted as a function call. In the vim-javascript plugin [this is how they seem to support that](https://github.com/pangloss/vim-javascript/blob/9f3ecf4595fb8a9b0b34e862001daccbbf61d17c/syntax/javascript.vim#L28).

Is this supported by YATS? I seem to be getting [`typescriptIdentifierName `](https://github.com/HerringtonDarkholme/yats.vim/blob/6b8e9876b901953abf2a5a58e34239498f569b53/syntax/typescript.vim#L69) even when the code in question is a function call.

**Comment by HerringtonDarkholme** [comment]
Pull request is welcome.
