### ISSUE TITLE
Generic with default generic breaks rest of highlighting for declaration

### ISSUE THREAD

**Issue by dsifford** [HerringtonDarkholme/yats.vim#122]
Just getting this written down so I don't forget. Might take a stab on this later.

**Quick example:**

```ts
  interface FooBar<T extends Record<string, any> = Record<string, any>> {
//                                                                    ^ breaks here
      foo: string;
      bar: number;
  }
```
It appears the syntax thinks the generic stops at the first `>` and it doesn't know what to do with the next one.

**Comment by dsifford** [comment]
The same issue also occurs with functions.

```ts
  function foobar<T extends Record<string, any> = Record<string, any>>(foo: T): T;
//                                                                   ^ breaks here
```

**Comment by nicolidin** [comment]
I have exactly this problem, have you found a solution?

**Comment by HerringtonDarkholme** [comment]
Sorry for the late reply, I have fixed the problem!
