### ISSUE TITLE
Matching curly braces

### ISSUE THREAD

**Issue by gunar** [HerringtonDarkholme/yats.vim#124]
Thanks for this great library.

Would it be possible to implement or extend it to add highlighting of matching curly braces? How would I go about that?

Thank you.

**Comment by HerringtonDarkholme** [comment]
By matching curly braces, if you mean something like the image, it's already supported by vim.

![image](https://user-images.githubusercontent.com/2883231/61340648-ca4a0780-a875-11e9-937f-597c3ae9c08b.png)

Otherwise, you might like https://github.com/luochen1990/rainbow.

**Comment by gunar** [comment]
Thank you for the detailed answer, @HerringtonDarkholme.

I was wondering if we could make the brackets get matching colors, even when they're not hovered. Do you think it'd be possible?

Thank you.
