### ISSUE TITLE
! is both a prefix and a postfix operator

### ISSUE THREAD

**Issue by taralx** [HerringtonDarkholme/yats.vim#134]
Currently ! is only covered by typescriptUnaryOp, which represents prefix operators. But it is also the non-null coercion (postfix) operator. Expressions like this end up mis-highlighted:

```typescript
{
  fieldA: expr!.fieldB,
}
```

`fieldB` gets highlighted by typescriptObjectLabel, but it shouldn't.

**Comment by HerringtonDarkholme** [comment]
It has already been fixed!

**Comment by taralx** [comment]
Okay, but I don't think the fix is correct. This still fails to highlight correctly:

```typescript
{
    fieldA: (expr!).fieldB,
}
```
