### ISSUE TITLE
Typescript 3.7 Support

### ISSUE THREAD

**Issue by adberard** [HerringtonDarkholme/yats.vim#141]
https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-beta/

- [x]  Optional Chaining `let x = foo?.bar.baz();`
- [x]  Nullish Coalescing `let x = foo ?? bar();`

**Comment by dmix** [comment]
I've been waiting for optional chaining forever. It's what's held me back from using the babel plugin for over a year now.

**Comment by jlmurphysa** [comment]
Is anybody working on implementing this yet? Use of the new optional chaining operator seems to break my syntax highlighting quite badly:

![image](https://user-images.githubusercontent.com/6492155/68378327-93fe0400-0154-11ea-8346-60b8caf71514.png)

**Comment by dmix** [comment]
I tried all of the typescript vim plugins this past week and none of them support it yet.

I'm considering doing it myself tomorrow evening if I get some time...

**Comment by HerringtonDarkholme** [comment]
Thanks to @rhysd ! This is supported now!
