### ISSUE TITLE
Does yats give me descriptions of syntax errors if they are in the file?

### ISSUE THREAD

**Issue by SnowCone161803** [HerringtonDarkholme/yats.vim#145]
if I open a typescript file that has no errors, then delete an `import` statement it highlights the usages of the import.

However, I can't find a description of the error message anywhere.

Does this exist in yats?

**Comment by HerringtonDarkholme** [comment]
Error message is usually shown by neomake/syntastic or language server plugins. They all do amazing jobs in error reporting so yats won't include such functionality.

**Comment by SnowCone161803** [comment]
cool, thanks for the help!
