### ISSUE TITLE
Syntax breaks where () are used for function delcaration in object

### ISSUE THREAD

**Issue by subev** [HerringtonDarkholme/yats.vim#146]
When we have function defined like this:
```const foo = {
    someFun(): someType {
    }
```
inside a class - the syntax braeks. See attached screenshots. line 45 - function name **default**

![Screenshot 2019-10-30 at 18 27 16](https://user-images.githubusercontent.com/1330872/67878036-58a37a00-fb43-11e9-914b-f7ce4b59cdce.png)
![Screenshot 2019-10-30 at 18 27 05](https://user-images.githubusercontent.com/1330872/67878040-59d4a700-fb43-11e9-8579-56271ec47efa.png)

The file to play with:
[sample.ts.txt](https://github.com/HerringtonDarkholme/yats.vim/files/3790122/sample.ts.txt)

**Comment by HerringtonDarkholme** [comment]
This should not be hard to fix.

The decorator call isn't highlighted as function call so the object literal is highlighted as block.

**Comment by HerringtonDarkholme** [comment]
fixed

**Comment by subev** [comment]
I tried to use the latest version but it does not seem to make any difference?

**Comment by si3792** [comment]
I'm also hitting this problem with the latest version

**Comment by subev** [comment]
The problem is probably in the keyword 'default' itself, if I remove a character from it, the highlighting seems to be working properly. @HerringtonDarkholme

**Comment by HerringtonDarkholme** [comment]
This is what I see in reduced example.
<img width="896" alt="Screen Shot 2020-01-11 at 10 42 57 PM" src="https://user-images.githubusercontent.com/2883231/72205973-e563a000-34c3-11ea-93aa-ed25ecb78acf.png">

**Comment by subev** [comment]
Thank you for sharing. It works when I disable vim-polyglot and leave just yats.vim, and it feels great! I wonder what could make a difference since polyglot's typescript support is actually again yats.vim, probably there are some other syntax scripts that are interfering </3.
Thank you once again, I know it's outside of your area of control but it would be great if they could be pointed in the right direction so it can just work properly :).

**Comment by HerringtonDarkholme** [comment]
That's because vim polyglot has its own fork of yats! It would be nice if it can be updated!
