### ISSUE TITLE
Update the single-file version please

### ISSUE THREAD

**Issue by brammool** [HerringtonDarkholme/yats.vim#150]
I have also added the typescriptreact.vim syntax and split off the common code
to typescriptcommon.vim.
You can find the file here: https://github.com/vim/vim/blob/master/runtime/syntax/typescriptreact.vim
Can you please check for updates since this single file version was made and create new files for the next upcoming release of Vim?

**Comment by HerringtonDarkholme** [comment]
Sure, I will do it!

**Comment by HerringtonDarkholme** [comment]
The generated files locate at `merged`

**Comment by brammool** [comment]
> The generated files locate at `merged`

Thanks!

Before including this in Vim I made the following changes.  I hope you
can integrate that in your merge script for next time.

- Move the common part between the two files to typescriptcommon.vim
  This starts at "Define the default highlighting" and ends near "unlet
  did_typescript_hilink".
- Added header to the common file.
- Change "highlight def link" and "HiLink", use "hi def link"
  everywhere.  Remove defining HiLink and remove the condition on
  did_typescript_hilink
- Add code to set 'cpo' to support line continuation
- Some indents and other minor changes.

-- 
hundred-and-one symptoms of being an internet addict:
145. You e-mail your boss, informing him you'll be late.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
