### ISSUE TITLE
Return type in JSX handlers breaks highlighting

### ISSUE THREAD

**Issue by Vanuan** [HerringtonDarkholme/yats.vim#155]
Without return type:
![image](https://user-images.githubusercontent.com/361985/71776387-abf9d480-2f99-11ea-9e6c-afda72c49ba3.png)

With return type:
![image](https://user-images.githubusercontent.com/361985/71776390-b3b97900-2f99-11ea-88ba-b83cafdd893e.png)

I've noticed similar issue with a comment "fundamental problem with arrow function detection". But how it works in typescript-vim + vim-jsx-typescript  plugin pair:

![image](https://user-images.githubusercontent.com/361985/71776413-f9764180-2f99-11ea-8091-6e90be70854a.png)

Maybe reuse is possible: https://github.com/peitalin/vim-jsx-typescript/blob/master/after/syntax/tsx.vim

**Comment by Vanuan** [comment]
Works if not used inside an arrow function:

![image](https://user-images.githubusercontent.com/361985/71777297-78717700-2fa6-11ea-9cbe-81837a53d62d.png)

So it must be some kind of issue with greedy matching nested arrow functions.

**Comment by Vanuan** [comment]
I've commented out these:

```
"syntax match   typescriptArrowFuncDef          contained /\K\k*\s*=>/
"  \ contains=typescriptArrowFuncArg,typescriptArrowFunc
"  \ nextgroup=@typescriptExpression,typescriptBlock
"  \ skipwhite skipempty
"
" TODO: optimize this pattern
"syntax region   typescriptArrowFuncDef          contained start=/(\_[^)]*)/ end=/=>/
"  \ contains=typescriptArrowFuncArg,typescriptArrowFunc,typescriptTypeAnnotation
"  \ nextgroup=@typescriptExpression,typescriptBlock
"  \ skipwhite skipempty keepend
```

Function arguments are not highlighted now, but at least JSX highlighting doesn't break.

**Comment by Vanuan** [comment]
Ok, the issue is not with nested arrow function, but with parenthesis.

This works:

  const b = <button onClick={(a: MouseEvent): void => {}} ></button>;

But this doesn't:

  const b = (<button onClick={(a: MouseEvent): void => {}} ></button>);


![image](https://user-images.githubusercontent.com/361985/71788391-633e2c00-302a-11ea-9402-6e0408f0363a.png)

Which means that yats treats any opening parenthesis till the first arrow as arrow function definition. And it only happens when there's JSX between opening parenthesis and arrow.

**Comment by HerringtonDarkholme** [comment]
Hi! Thanks for your deep investigation!

I think the problem should be the fundamental issue in how yats detects arrow function… I am considering how vscode handle such problem…

**Comment by Vanuan** [comment]
Worked out a minimal case. Apparently, doesn't have anything to do with JSX.

![image](https://user-images.githubusercontent.com/361985/71791207-c933af00-303c-11ea-8694-9050cd5c343b.png)

**Comment by Vanuan** [comment]
See proposed solution in #156

**Comment by Vanuan** [comment]
If you're interested, VSCode used Text Mate grammar interpreter which is based on Oniguruma syntax engine. Grammar file for TypeScript is here: https://github.com/microsoft/TypeScript-TmLanguage/blob/master/TypeScript.YAML-tmLanguage

Arrow function definition is here:
https://github.com/microsoft/TypeScript-TmLanguage/blob/b7ef0941e38d56292d19ee7706a558dbff6c3a35/TypeScript.YAML-tmLanguage#L778-L817

**Comment by HerringtonDarkholme** [comment]
I found the ecma standard has limited what identifier can follow arrow function parameter. 

https://tc39.es/ecma262/#prod-ArrowParameters

It might help us to find some pattern in arrow function.

**Comment by Vanuan** [comment]
@HerringtonDarkholme If I'm reading this correctly, syntactically `ArrowParameters` can be of any parenthesized expression. The only limitation is that arrow cannot be preceded with end of line.

**Comment by Vanuan** [comment]
I think the fundamental issue is that you can't have perfect syntactic highlighting for a [context-free grammar](https://tc39.es/ecma262/#sec-notational-conventions) using regular expressions. You can only highlight the [lexical grammar](https://tc39.es/ecma262/#sec-ecmascript-language-lexical-grammar) using vim syntax definitions.

While you can define some subset of a context-free grammar, there will always be some edge cases you couldn't solve using regex.
