### ISSUE TITLE
Syntax highlighting stumbles after a function call inside a JSX tag

### ISSUE THREAD

**Issue by geomaster** [HerringtonDarkholme/yats.vim#16]
With a buffer containing the following:
```tsx
let a = (
    <b>
        { f() }
    </b>
);

let someVar = 20;
someFn(200);
// ...
```
For some reason, afer the closing parenthesis in `f()`, the syntax highlighter enters some weird mode, subsequently highlighting 'let' as an error token and failing to correctly highlight the following lines:
![screenshot from 2017-02-12 03-23-12](https://cloud.githubusercontent.com/assets/968875/22859147/af22baa4-f0d2-11e6-8989-09d41cc84ac0.png)

Changing `f()` to `f` solves the problem, as does adding any additional tokens before, in most cases:
![screenshot from 2017-02-12 03-23-30](https://cloud.githubusercontent.com/assets/968875/22859148/af261654-f0d2-11e6-8a10-3ab8a0aee353.png)
![screenshot from 2017-02-12 03-25-56](https://cloud.githubusercontent.com/assets/968875/22859163/167cc1d6-f0d3-11e6-8894-0566347fdb70.png)
![screenshot from 2017-02-12 03-26-17](https://cloud.githubusercontent.com/assets/968875/22859162/167c8608-f0d3-11e6-9125-1ba51dc21399.png)

I have no idea how Vim's syntax highlighting works internally, so I'm kind of lost here :(

**Comment by HerringtonDarkholme** [comment]
I'm sorry but JSX is not supported.

**Comment by hdra** [comment]
Hi, @HerringtonDarkholme 

Just to clarify, this means TSX/*.tsx file is not supported?

**Comment by HerringtonDarkholme** [comment]
No, I won't support tsx.

**Comment by hdra** [comment]
Gotcha.

In that case, would you consider reverting [this commit](https://github.com/HerringtonDarkholme/yats.vim/commit/f2072fceefa939f2670c897e9e4e1749594f6447)?

Or maybe use `setfiletype` instead as to not override other plugins that may handle it?

**Comment by HerringtonDarkholme** [comment]
@hdra Thanks for the suggestion. I think it is a reasonable choice. I have removed tsx from filetype plugin.
