### ISSUE TITLE
Incorrect syntax highlighting

### ISSUE THREAD

**Issue by mhmdanas** [HerringtonDarkholme/yats.vim#162]
`yats.vim` highlights this incorrectly:
```typescript
type Foo =
    | { bar: string }
    | { baz?(): number }

function bat() {
    // stuff...
}

const x = y + 1;
```

Screenshot:

<img width="173" alt="Screen Shot 2020-02-06 at 8 08 28 PM" src="https://user-images.githubusercontent.com/32234660/73960720-717ab300-491c-11ea-9dbe-02f1d68d4068.png">

This doesn't happen if `baz?` is replaced with `baz`:

<img width="166" alt="Screen Shot 2020-02-06 at 8 08 41 PM" src="https://user-images.githubusercontent.com/32234660/73960744-79d2ee00-491c-11ea-8d37-3b3ce6b3b277.png">

**Comment by rhysd** [comment]
I'll make a fix for this.
