### ISSUE TITLE
Issue when opening basic files

### ISSUE THREAD

**Issue by sheerun** [HerringtonDarkholme/yats.vim#164]
When one is using yats.vim, opening basic script (programming language) results in an error. This is probably because you are using `syntax/basic` folder and there exists such filetype. Could you rename this folder to something else? e.g. `syntax/typescript-basic`

Reference: https://github.com/sheerun/vim-polyglot/issues/466

**Comment by HerringtonDarkholme** [comment]
Thanks for reporting! I will first apply the hotfix mentioned in the linked issue.

Later I will rename the directory! Thanks！
