### ISSUE TITLE
JSX return value misidentified as arrow function

### ISSUE THREAD

**Issue by jonsmithers** [HerringtonDarkholme/yats.vim#166]
I'm using `vim --clean` to reproduce this.

```typescript
const x = () => {
  return (
      <Component
        onChange={(): void => {}}
      />
    );
};
```

In this example `<Component` is identified as a `typescriptArrowFuncDef` region. It should be identified as a `tsxTag`.

(I'm using `:echo map(synstack(line("."), col(".")), "synIDattr(v:val, 'name')")` to diagnose this).

I was in a file where the syntax highlighting got completely off track at a specific point, such that vim eventually ended up highlighting the the entire rest of the file as a `typescriptTemplate` region. I boiled it down to this issue.

**Comment by HerringtonDarkholme** [comment]
Hi, thanks for reporting.
However I cannot reproduce the problem. Could you please use a minimal vimrc and update yats to latest version?

![image](https://user-images.githubusercontent.com/2883231/75954712-4a99a780-5eef-11ea-9345-aa51e4121ea9.png)

**Comment by jonsmithers** [comment]
It turns out I can't reproduce this using the plugin, so it must be fixed in the latest version. However, as I understand it, vim is shipped with yats.vim's syntax files. So, in vim 8.2.350, without this plugin installed, I can reproduce the issue. In [`$VIMRUNTIME/syntax/typescriptreact.vim`](https://github.com/vim/vim/blob/master/runtime/syntax/typescriptreact.vim), it says `" Last Change:	2019 Nov 30`. So maybe I just need to wait for vim to update its typescriptreact runtime files or install this plugin.
