### ISSUE TITLE
How to customize highlight linking.

### ISSUE THREAD

**Issue by laino** [HerringtonDarkholme/yats.vim#169]
``typescriptTypeReference`` links to ``Identifier`` even though ``typescriptPredefinedType`` links to ``Type``. 

This looks really weird with a lot of colorschemes.

For now I have ``highlight! link typescriptTypeReference Type`` in my vimrc.

**Comment by lucasprag** [comment]
Yeah, I had also to manually support `typescriptTypeReference` on my [colorscheme](https://github.com/lucasprag/simpleblack), I'm happy to create a PR for it if people are ok with making this link.

**Comment by HerringtonDarkholme** [comment]
Pull request is welcome.
