### ISSUE TITLE
Priority of snippets

### ISSUE THREAD

**Issue by shirohana** [HerringtonDarkholme/yats.vim#17]
Excuse me, may you set a lower priority like -50 (same as vim-snippets) or -49 as default?

It will get more compatible with other UltiSnips plugins and users can override your snippets with a default priority ฅ' ω 'ฅ

**Comment by shirohana** [comment]
btw, how about set a tabstop at the end of line or a newline for "import reference" snippet?

like

    /// \<reference path='${1:file}' />$0

or

    /// \<reference path='${1:file}' />
    $0

**Comment by HerringtonDarkholme** [comment]
Hi, thanks for trying out yats.

I don't know where I can set snippet priority. According to the doc https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L224-L245, it seems you can specify your snippet loading order.

Builtin snippet cannot be customized. You can writing your own and then load it to override yats.

**Comment by shirohana** [comment]
You can set snippet priority by 'priority' keyword at the beginning of line. It looks like this https://github.com/honza/vim-snippets/blob/master/UltiSnips/javascript.snippets

Maybe this paragraph would help (´・ω・)ﾉ https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L619

**Comment by HerringtonDarkholme** [comment]
Thanks for pointing out! I don't know that! 

Negative priority seems to be a better practice. Will add it!

**Comment by shirohana** [comment]
Thanks for your adoption, too (๑• ω •๑)

**Comment by HerringtonDarkholme** [comment]
And your proposed `/// reference` snippet is definitely better the current one!
Also added! Thanks!
