### ISSUE TITLE
GitHub workflow to show syntax changes

### ISSUE THREAD

**Issue by Schniz** [HerringtonDarkholme/yats.vim#171]
Hi,
[I have a fork with an open PR](https://github.com/Schniz/yats.vim/pull/2) that shows a GitHub workflow that attaches images of the current state of the plugin, using the test cases (`test/test.ts` and `test/test.tsx`):

![Workflow demo](https://user-images.githubusercontent.com/2054772/77438568-a79dc480-6dee-11ea-9e93-848fcfd9f2a5.png)

I think it's a good way to easily show the differences with an automated way, and also can help when providing "failing" test cases. I'm using the default Vim colorscheme but it can change as well (maybe to use the same colorscheme as you use in the readme?)

It's currently working on my fork, but should work once I'll make a PR/merge to your repo. Does it make any sense to you?

Again, thanks for the awesome plugin! 👏

**Comment by HerringtonDarkholme** [comment]
Cool! Would you like submit a pull request? Thanks a lot!
