### ISSUE TITLE
Highlight return keyword

### ISSUE THREAD

**Issue by glepnir** [HerringtonDarkholme/yats.vim#183]
Doesn't get the syntax group of `return`
![image](https://user-images.githubusercontent.com/41671631/81502579-65363580-9311-11ea-9052-00122cb35e9f.png)

**Comment by rhysd** [comment]
This is not reproducible in my local

<img width="642" alt="スクリーンショット 2020-05-12 10 41 27" src="https://user-images.githubusercontent.com/823277/81629046-2dc4a780-943d-11ea-9efd-ec41c452ec62.png">

**Comment by HerringtonDarkholme** [comment]
@glepnir could you please paste the whole file and keep your vimrc minimal? Minimal means you have to disable all other plugins and just keep yats active.

**Comment by glepnir** [comment]
@HerringtonDarkholme  Ok found the problem， seems it conflict with `luochen1990/rainbow`
