### ISSUE TITLE
why is try/import/export/module/expceptions Special and not Keyword?

### ISSUE THREAD

**Issue by gko** [HerringtonDarkholme/yats.vim#188]
Thank you for your work ❤️

Just a question on reasoning behind making these a `Special`. If you want I can make a PR making them `Keyword`.

https://github.com/HerringtonDarkholme/yats.vim/blob/7978f7d52e1cfbdba1d17951c7bd4be527807e4e/syntax/common.vim#L104-L111

**Comment by HerringtonDarkholme** [comment]
Thanks for the suggestion. You can HiLink the syntax in your vimrc. I choose Special because it makes TS file visually rhythmic by removing repetitive keyword color.
