### ISSUE TITLE
foldBraces Error

### ISSUE THREAD

**Issue by cmather** [HerringtonDarkholme/yats.vim#19]
Thanks for the awesome plugin! I'm getting an error that I think is related to this plugin, as the error goes away when I uninstall the plugin and reappears when I reinstall it. See the attached screenshot for the error: "No such highlight group name: foldBraces". I took a quick tour through the source and couldn't find anything but maybe I'm missing something. Many thanks if you know what might be causing it!

![screen shot 2017-03-30 at 7 39 38 pm](https://cloud.githubusercontent.com/assets/262179/24534166/0948a8c2-1581-11e7-8521-ce5abbf1d448.png)

**Comment by HerringtonDarkholme** [comment]
Could you please provide a minimal vimrc?

`foldBraces` didn't even appear in yats source code. It probably is caused by another plugin.

**Comment by cmather** [comment]
Yeah I didn't see `foldBraces` in the source either so figured I might have missed something. And as I was preparing to upload my vimrc snippet I think I found it. -1 for my debugging skills. Not sure why the error goes away when I remove the plugin though, even though the vimrc stays the same. Maybe a red herring :-/

```vimrc
autocmd FileType typescript syn clear foldBraces
```

**Comment by cmather** [comment]
Confirming good to go now. Thanks for getting back so quickly :).
