### ISSUE TITLE
Installation Info in Readme

### ISSUE THREAD

**Issue by kylpo** [HerringtonDarkholme/yats.vim#2]
Would you please document how I can install and use this in the Readme?

Trying `NeoBundle 'HerringtonDarkholme/yats.vim'` is not doing the trick.

**Comment by HerringtonDarkholme** [comment]
Have you installed [NeoBundle](https://github.com/Shougo/neobundle.vim)? You have to install a proper plugin manager first.

I think I will update the Readme for other plugin managers, but not for vanilla installation.

**Comment by HerringtonDarkholme** [comment]
And this is my config.

```vimL
function FiletypeLoad(...)
    return {'autoload': { 'filetypes' : a:000 }}
endfunction

NeoBundleLazy 'HerringtonDarkholme/yats.vim',
			\FiletypeLoad('typescript')
```

**Comment by kylpo** [comment]
Ah, sorry. It was just conflicting with another plugin. The NeoBundle install did work.

Thanks so much for your work and quick reply!
