### ISSUE TITLE
How do I disable autocompilation every time I type?

### ISSUE THREAD

**Issue by sheldonkwok** [HerringtonDarkholme/yats.vim#20]
It's frustrating to see all the errors every time I type when I'm migrating a file to ts. I would like to disable compilation on typing and just compile on save.

**Comment by HerringtonDarkholme** [comment]
yats does not provide compiling on typing feature. I guess it's your other plugins.

**Comment by sheldonkwok** [comment]
Thanks! Will look into it more.

**Comment by sheldonkwok** [comment]
I didn't realize that YouCompleteMe was the culprit if anyone ever is curious too.
