### ISSUE TITLE
export default class breaks public/private/readonly/static

### ISSUE THREAD

**Issue by sheldonkwok** [HerringtonDarkholme/yats.vim#21]
public/private/readonly/static show up as errors when export default class is used
![screen shot 2017-05-23 at 10 50 58 am](https://cloud.githubusercontent.com/assets/1491201/26368240/ec3cf022-3fa5-11e7-861b-43b30f67b9f4.png)

**Comment by ebenoist** [comment]
I'm getting this as well, whats up?

**Comment by HerringtonDarkholme** [comment]
Sounds like class syntax isn't in typescriptExpression group, will fix it.

**Comment by HerringtonDarkholme** [comment]
Fixed in https://github.com/HerringtonDarkholme/yats.vim/commit/c8d92830107d5d17516b8937320421eade4c7c96
