### ISSUE TITLE
backtick(``) syntax highlighting is broken

### ISSUE THREAD

**Issue by SeungUkLee** [HerringtonDarkholme/yats.vim#217]
* `nvim --version` : v0.4.4
* OS : macOS Catalina 10.15.7

## Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC foo.ts 
```

Input the following code:

```typescript
const a = (msg: String) => {
        return {
                err: new Error(`${msg}`)
        }
}

const foo = 'foo';
const boo = 'boo';
```

## Actual behaviour

Everything after `` `) `` until the end of file is rendered in the same color.

<img src="https://user-images.githubusercontent.com/21017537/98612410-74855280-2337-11eb-9029-22739ab46b88.png" width="40%">

Related to #173

**Comment by NoahTheDuke** [comment]
I just encountered this.

**Comment by romanblanco** [comment]
I can break the syntax with this case:
![2021-01-26-112338](https://user-images.githubusercontent.com/1187051/105839355-4247d080-5fc9-11eb-91ad-b69edc5e0d3f.png)

After removing the comparing from ternary operator, the syntax is OK: 
![2021-01-26-112406](https://user-images.githubusercontent.com/1187051/105839353-41af3a00-5fc9-11eb-80d0-16d716e2de2f.png)

Also seeing issues with this:
![2021-01-26-112500](https://user-images.githubusercontent.com/1187051/105839351-4116a380-5fc9-11eb-8ff8-2d0b26b79296.png)



Going through changes, maybe something missing in https://github.com/HerringtonDarkholme/yats.vim/pull/204/files#diff-3842ed26fb5d78bb259e637f7f905eba74051c266e2374ffca6f003311008eb8R67

**Comment by kalda341** [comment]
Also encountering this when using generic templated strings such as the following:
``` typescript
db.sql<db.SQL>`${db.self} IN (${readableUsersFragment(user)})`
```

**Comment by bgenchel** [comment]
Also just encountered this, using YATS via vim-polyglot.
```
   const testClass = "testClassName"
    const environmentVariables = {
      // Added a dynamic parameter to force redeployment in the dev stacks
      TIMESTAMP: `${new Date().toISOString()}`,
      vpcId: vpc.vpcId,
      securityGroupName: securityGroup.securityGroupName,
      stage: props.stage
    }
```
In the above example, all text after the backtick in the "TIMESTAMP" format string is highlighted as a comment string. The closing bracket in the format string is highlighted as to show it being matched with the object opening bracket, as opposed to the opening bracket for the format string itself. 

I installed typescript-vim and this problem was corrected.

**Comment by erikc96** [comment]
Same issue, same solution ^

**Comment by HerringtonDarkholme** [comment]
I'm busy with my day jobs and other [projects](https://github.com/ast-grep/ast-grep). I will look at the issue recently. 
If you find this project useful, I would appreciate your [gratitude](https://github.com/sponsors/HerringtonDarkholme/)!
