### ISSUE TITLE
for-await-of incorrectly highlights const

### ISSUE THREAD

**Issue by sheldonkwok** [HerringtonDarkholme/yats.vim#22]
![screenshot from 2017-06-12 15-56-07](https://user-images.githubusercontent.com/1491201/27058699-b9ed75dc-4f87-11e7-839a-ae646c6a6b29.png)

`const` is incorrectly highlighted. This is new syntax in Typescript 2.3

**Comment by HerringtonDarkholme** [comment]
fixed in https://github.com/HerringtonDarkholme/yats.vim/commit/3bb50d3f12620fa6c8ca670d9b5927d9021f9336

**Comment by sheldonkwok** [comment]
I'm still running into this issue even after updating to 3bb50d3
