### ISSUE TITLE
region typescriptIndexExpr does not end?

### ISSUE THREAD

**Issue by phelipetls** [HerringtonDarkholme/yats.vim#232]
Taking for example the snippet below

```typescript
const arr = [1, 2, 3]
console.log(arr[3] || 4)
```

The opening bracket is correctly highlighted with `typescriptProperty`.

But the closing bracket is not. The region is not being closed for some reason.

I'm looking into it but it's not clear what's causing it because the definition of `typescriptIndexExpr` seems correct but for some reason is not being respected.

```vim
syntax region  typescriptIndexExpr      contained matchgroup=typescriptProperty start=/\[/rs=s+1 end=/\]/he=e-1 contains=@typescriptValue,typescriptCastKeyword nextgroup=@typescriptSymbols,typescriptDotNotation,typescriptFuncCallArg skipwhite skipempty
```

**Comment by phelipetls** [comment]
Seems like removing the nextgroup argument from typescriptIdentifierName works, but I'm sure this was needed at some point.

```
syntax match   typescriptIdentifierName        /\<\K\k*/
  \ nextgroup=@afterIdentifier
  \ transparent
  \ contains=@_semantic
  \ skipnl skipwhite
```

**Comment by phelipetls** [comment]
Nevermind, it breaks several other stuff :( sorry

**Comment by phelipetls** [comment]
Ok, so things appear to have improved after I removed the `:syn-pattern-offset` from the start and end pattern of `typescriptIndexExpr`. I don't know exactly why they were there so I'm not confident about this, I'll see if something strange pops up before submitting a PR.

**Comment by bodograumann** [comment]
I have an issue, where highlighting is broken after an index access. Could this be the same cause?
```typescript
const arr = [];
const x = { key: arr[idx] ?? "" };
const y = 5;
```

**Comment by phelipetls** [comment]
I think so, just checked out my PR and it is fixed there. Will try to get it merged.
