### ISSUE TITLE
function with generic missing highlighting in object arguments

### ISSUE THREAD

**Issue by sheldonkwok** [HerringtonDarkholme/yats.vim#24]
![screenshot from 2017-07-20 14-58-35](https://user-images.githubusercontent.com/1491201/28440759-87be9f4e-6d5c-11e7-9734-bb6a1cf4671d.png)

When using a function with a generic, the object being passed in is missing highlighting on some keys and values. `raw` and `true` should be highlighted.

**Comment by HerringtonDarkholme** [comment]
Please see #30
