### ISSUE TITLE
Support for Conceal

### ISSUE THREAD

**Issue by Industrial** [HerringtonDarkholme/yats.vim#241]
Hello. I use https://github.com/pangloss/vim-javascript for JavaScript because it supports concealing characters to make the document look a lot nicer. I would love to use this with TypeScript as well (since I don't write any JavaScript anymore. I do it all in TypeScript).

Is it possible to copy/support the same kind of concealing in this plugin?

gr,

Tom

**Comment by HerringtonDarkholme** [comment]
Sounds cool! Thanks for the advice. 

Pull request is welcome. Or I will find some time to update it myself when I'm available.

**Comment by HerringtonDarkholme** [comment]
fixed in 156bacdb08f79bd2c7b559e2bdac985bfb32e4f4

**Comment by Industrial** [comment]
Awesome, thank you!
