### ISSUE TITLE
Conflicts with Rainbow

### ISSUE THREAD

**Issue by elleven11** [HerringtonDarkholme/yats.vim#244]
Hello,
This plug-in conflicts with  luochen1990/rainbow, is there anything that we can do to fix it?

Thank you.

**Comment by HerringtonDarkholme** [comment]
Personally I don't use rainbow. I don't think yats is compatible with rainbow though, if rainbow is based on syntax matching. 
If rainbow can change their implementation to directly add highlight group to parens, the problem might be solved.
