### ISSUE TITLE
Performance issues?

### ISSUE THREAD

**Issue by epeli** [HerringtonDarkholme/yats.vim#25]
I tried to switch to yats from [leafgarland/typescript-vim](https://github.com/leafgarland/typescript-vim) but unfortunately I had to revert back because it made scrolling very laggy.

Anyone else seeing similar issues?

I'm on Neovim and use it from the terminal along tmux.

**Comment by HerringtonDarkholme** [comment]
I didn't see any noticeable lag on my code base.

Maybe you can provide some laggy example.

**Comment by werber** [comment]
I confirm it. It happens if you have f.g. large TS class for 1k LoC (in my case it's 1022 LoC) and you try to defined private property, it starts hanging. If you are interested in my PC characteristics, here they are:
Intel i7 7800X 3.5Ghz 6 cores/12 threads
40 GB RAM 2600Mhz
M.2 250GB
So here couldn't be any issues with PC not being able to handle loads. Only 10GB of 40 was used at that moment and when I start typing with yats enabled one core gets loaded by 100% for few seconds. 

---

Prepared two gifs, first with yats enabled, second without.
![with_yats](https://user-images.githubusercontent.com/1785535/33231841-8610806a-d204-11e7-924a-70db2c4fda34.gif)
![without_yats](https://user-images.githubusercontent.com/1785535/33231843-89c4c0c2-d204-11e7-8231-6661123d44e2.gif)

**Comment by HerringtonDarkholme** [comment]
This is probably caused by your autocompletion plugin.

My suggestion is turning off some plugin and try again. 
But sadly, bad performance is somehow by design. I have constantly optimize runtime performance but it turns out that advanced highlighting requires much regex matching.

**Comment by werber** [comment]
Nope. Removed all, left only yats, one theme and airline. 
Probably issue only for large ts files which takes time to be compiles/traversed by plugin.
P.S. Awesome plugin, really love it!
![image](https://user-images.githubusercontent.com/1785535/33232196-5a6882c2-d20a-11e7-8296-0b779b253a73.png)

**Comment by HerringtonDarkholme** [comment]
I'm sorry to hear that. By the way, would you like to provide one big file where you encountered the problem?

**Comment by werber** [comment]
Sorry, I can't. I'm not allowed to show full listing. 
But I'll try to find similar 1k+ ts files which are open source and open it with my current configuration.

**Comment by HerringtonDarkholme** [comment]
FYI, I use yats in huge file like TypeScript compiler (about 20k lines of code). I didn't observe highlighting lag.

**Comment by pmlamotte** [comment]
I'm also experiencing a ton of lag. Using typescript-vim is much smoother but it has far less highlighting as well. I also don't notice lag with other filetypes like c# or js.

**Comment by HerringtonDarkholme** [comment]
I found a significant performance gain chance in the highlight syntax. Reopen.

**Comment by HerringtonDarkholme** [comment]
I have implemented a lot of performance improvements in master branch.

You can try it out!

For me, yats in Vue single file component is also very performant now.

**Comment by dsifford** [comment]
I'm unfortunately getting a ton of lag in small- to medium-sized `.tsx` files. 

Speed delays are most seen when editing expressions nested jsx components.

Syntax is pretty friggen awesome, so this is sort of a bummer.

**Comment by HerringtonDarkholme** [comment]
@dsifford can you provide an example tsx file?

Also, do you have other syntax highlight plugin installed?

**Comment by tomaskallup** [comment]
I've ran into this as well, here is a file which is problematic for me: https://gist.github.com/tomaskallup/14f29f7e7fa30d200d1390cb5d9cbb95
If I start scrolling from the top it seems okay, but upon reaching line ~40 it start really struggling. There is also a small delay when typing.
Tested with `vim-plug` for plugin management and `yats` only.

**Comment by tomaskallup** [comment]
I think I see the problem, it's the nested jsx tags!
For example this code:
```typescript
    <div>
        <div>
            <label>Test label</label>
            <div>
                <div>
                    <div>
                        <div>
                            <div>
                                <div>
                                    <p>Hello</p>
                                    <p>Hello</p>
                                    <p>Hello</p>
                                    <p>Hello</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
```
The nested `<p>` element is in these highlight groups: `['tsxRegion', 'tsxRegion', 'tsxRegion', 'tsxRegion', 'tsxRegion', 'tsxRegion', 'tsxRegion', 'tsxRegion', 'tsxRegio
n', 'tsxRegion', 'tsxCloseTag', 'tsxIntrinsicTagName']`.

I'll mess around with this to see if I can figure out a way to get rid of the tsxRegion duplication.

**Comment by tomaskallup** [comment]
Alright, for me the problem seems to be cause by `set relativenumber`. I found a discussion here https://github.com/vim/vim/issues/1735
Seems like vim does a full resyntax everytime it scrolls. Even though other tsx plugins work better with `relativenumber`, yats is probably the most complete one.
Although plugin which I use for javascript.jsx seems to be fine even with `relativenumber` on same file which makes yats struggle. I use https://github.com/mxw/vim-jsx, it just makes js work with xml with some addition, making it almost native, since xml is supported natively. Maybe this could be somehow adapted by yats?

**Comment by Schniz** [comment]
YATS have become faster and faster, but arrow functions still cause a huge lag that makes it unusable:

```
  TOTAL      COUNT  MATCH   SLOWEST     AVERAGE   NAME                   PATTERN
  5.663737   174    4       1.892243    0.032550  typescriptArrowFuncDef (\(\_s*[a-zA-Z\$_\[]\_[^)]*\)*)\s*=>
```

that's 1.89s(!) for the slowest one (I only have one function, the 4 matches are made by scrolling), and this is its code

```ts
    this.setup = () => Promise.resolve(result);
```

**Comment by Schniz** [comment]
YATS still doesn't work for me, on simple cases. It freezes neovim and on Vim 8 it says `'redrawtime' exceeded, syntax highlighting disabled`.

Here's a way to reproduce it:

Go to vim and `:e file_without_extension` so you'll open a file without any filetype inferred. Write the following contents:

```ts
wrapper(
  fn(input, a => a.a_very_long_text.another_very_long_text[0]),
)
```

Now run `:set filetype=typescript` and see it fails

**Comment by HerringtonDarkholme** [comment]
I'm on neovim and doesn't observe any performance issue.

Please keep you vimrc minimal: that is, uninstall all other plugins. And try again.

**Comment by Schniz** [comment]
I've commented out all of the vundle plugins and it still doesn't work, does the test case I mentioned works well for you? Maybe I need to actually _delete_ all my plugins from `~/.vim`

**Comment by tomaskallup** [comment]
I've tried it on my heavy neovim configuration and no problems. Also seems to work fine with just yats installed.

**Comment by Schniz** [comment]
Found that. I had `set re=1` since my Ruby days. It made everything slow. Now it works great! Thanks!

**Comment by jponc** [comment]
> Found that. I had `set re=1` since my Ruby days. It made everything slow. Now it works great! Thanks!

This solved my issue as well! cheers @Schniz

**Comment by AZanellato** [comment]
Would you mind putting a note about this on the README?

I just hit the problem because of `re=1` as well, it broke on a kinda small file (around 200 lines)

**Comment by HerringtonDarkholme** [comment]
@AZanellato Sure! I will update it!

**Comment by AZanellato** [comment]
Thank you so much! :heart:

**Comment by dvogt23** [comment]
I had the same issue (`'redrawtime' exceeded, syntax highlighting disabled`) with following option in vimrc: `set regexpengine=1`. The deletion was the fix... maybe it helps someone, too.

**Comment by zachbai** [comment]
@HerringtonDarkholme The README suggests to add `set re=1` in your vimrc, which is in fact the opposite of the recommended fix here -- these performance issues are incurred when `re=1` so `set re=1` should be _removed_ from your vimrc.
