### ISSUE TITLE
TS 4.5 "type Modifiers on Import Names" breaks highlighting

### ISSUE THREAD

**Issue by roper79** [HerringtonDarkholme/yats.vim#251]
`import { someFunc, type BaseType } from "./some-module.js";`

https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#type-on-import-names

**Comment by vegawong** [comment]
The same issue！

**Comment by c0per** [comment]
Same here. I find this plugin (https://github.com/leafgarland/typescript-vim) to work just fine. Maybe yats needs an update for this syntax.

**Comment by lantw44** [comment]
It seems it is still broken  if there is a default import.
![2022-07-04 18-11-24 的螢幕擷圖](https://user-images.githubusercontent.com/3016644/177148737-a43c517f-d8b1-4c86-9916-9037089c3dd3.png)

**Comment by AllTradesz** [comment]
> It seems it is still broken if there is a default import. ![2022-07-04 18-11-24 的螢幕擷圖](https://user-images.githubusercontent.com/3016644/177148737-a43c517f-d8b1-4c86-9916-9037089c3dd3.png)

yep, same here

**Comment by char101** [comment]
Adding this in `after/syntax/typescript.vim` seems to fix the issue

```viml
syntax region  typescriptImportBlock           matchgroup=typescriptBraces start=/{/ end=/}/ contains=typescriptImportType,typescriptIdentifierName
```

The issue being `{...}` is matched as `typescriptBlock` which contains `typescriptAliasDeclaration` which contains `typescriptAliasKeyword` which is `type`, so we define another `{...}` block named `typescriptImportBlock` which only contains select import syntaxes.
