### ISSUE TITLE
`set iskeyword+=:` breaks highlighting

### ISSUE THREAD

**Issue by KonradHoeffner** [HerringtonDarkholme/yats.vim#253]
### Steps to reproduce

1. Put `set iskeyword+=:` in `~/.vimrc`
2. Save the following file as `test.ts` and open it in Vim or Neovim:

```ts
const x =
{
    onClickFunction: (event) => {
        const body = `${1+1}`;
        console.log("The rest of the file is highlighted incorrectly");
    }
}
x.onClickFunction(null);
```
![Screenshot](https://user-images.githubusercontent.com/839577/153863234-f6851209-e8f6-4f0d-ae4d-d99d331876b2.png)

### Expected behaviour

The line `thisFunctionIsShownAsLiteralButItIsntOne();` should be highlighted as a function but it is shown as a literal.

### Details and Proposed Change

This issue was originally raised at https://github.com/vim/vim/issues/9772, where @lacygoill proposed a patch to resolve this issue.

**Comment by HerringtonDarkholme** [comment]
`:` is not keyword in TypeScript. I wonder why the config is added?

**Comment by KonradHoeffner** [comment]
To be honest this was only added to get easier word traversal with the 'w' key, mostly for LaTeX, to easier delete parts of labels, and I probably should make this specific to certain file types, however I thought it better to still raise it here in case this effect is not intended and helps prevent future issues with similar causes.
