### ISSUE TITLE
TSX highlighting is thrown off when a React expression is wrapped in parens

### ISSUE THREAD

**Issue by tremby** [HerringtonDarkholme/yats.vim#256]
This code renders correctly:

```tsx
function thing() {
  return <div>{true && <p>{"x"}</p>}</div>;
};
```
![1](https://user-images.githubusercontent.com/199635/166847582-a4626dc6-31de-4b56-9607-bc728e468466.png)

but if I add parens (which is common in JSX/TSX like this) it no longer renders correctly:

```tsx
function thing() {
  return (
    <div>{true && <p>{"x"}</p>}</div>
  );
};
```
![2](https://user-images.githubusercontent.com/199635/166847592-4005c3e3-f492-43a2-bd17-6c9a4b8d87e9.png)

It breaks further if I add more linebreaks and parens, which is also common:

```tsx
function thing() {
  return (
    <div>
      {true && (
        <p>{"x"}</p>
      )}
    </div>
  );
};
```
![3](https://user-images.githubusercontent.com/199635/166847928-0de20ad5-e834-41fa-b410-5ab869d58044.png)

**Comment by HerringtonDarkholme** [comment]
I cannot reproduce it. Are you on vim? Neovim is okay.

<img width="397" alt="image" src="https://user-images.githubusercontent.com/2883231/186968874-bfd13c0d-200d-49ae-b399-c7fc9d586245.png">

**Comment by tremby** [comment]
I trimmed some extra plugins and some configuration which I'm not really using any more, and this now all looks fine. Must have been a conflict somewhere.
