### ISSUE TITLE
.tsx with React wrongfully identifies multiline jsx

### ISSUE THREAD

**Issue by deltaskelta** [HerringtonDarkholme/yats.vim#26]
![screen shot 2017-12-07 at 11 11 52 am](https://user-images.githubusercontent.com/9424192/33695290-e7dd3cea-db3f-11e7-8b9e-272cd2a50111.png)

the first red highlighted `<Button>` has the highlight group `hi<typescriptTypeReference> trans<typescriptTypeReference> lo<Identifier>`

the second unhighlighted (multiline) `<Button>` has the highlight group `hi<typescriptIdentifierName> trans<typescriptIdentifierName> lo<typescriptIdentifierName>`

**Comment by HerringtonDarkholme** [comment]
I'm sorry but JSX isn't supported.
