### ISSUE TITLE
Detect embedded scripts in vue component

### ISSUE THREAD

**Issue by mcpeng** [HerringtonDarkholme/yats.vim#260]
Is yats.vim possible to detect embedded typescript in vue component?
```vue
<script lang="ts">
// ...
</script>

<script setup lang="ts">
// ...
</script>
```

I'm using [coc-volar](https://github.com/yaegassy/coc-volar), `yats.vim`, [vim-javascript](https://github.com/pangloss/vim-javascript) now. `coc-volar` can detect that correctly, but if I use `vim-javascript`, it detects that as javascript and overwrites `coc-volar`'s detection wrongly, I hope `yats.vim` can detect that correctly.

**Comment by HerringtonDarkholme** [comment]
It is supported in vim-vue. 
https://github.com/posva/vim-vue/blob/master/syntax/vue.vim#L48

<img width="790" alt="image" src="https://user-images.githubusercontent.com/2883231/184655751-d4057449-5033-4e7f-8155-614d7a3f64c3.png">
