### ISSUE TITLE
variables with $ suffix break syntax highlighting

### ISSUE THREAD

**Issue by rain9441** [HerringtonDarkholme/yats.vim#262]
In Angular it is convenient to use the $ symbol as part of variable names as a way to indicate it is an Observable<>.

The syntax highlighting breaks when the $ symbol is used as part of a variable.

![image](https://user-images.githubusercontent.com/7594212/217329277-3d290e75-7e92-4ed9-8b07-b59f5c95b376.png)

**Comment by HerringtonDarkholme** [comment]
![image](https://github.com/HerringtonDarkholme/yats.vim/assets/2883231/df4c79b5-edc6-467d-b116-468c5f0c6c57)

I cannot reproduct it.
