### ISSUE TITLE
Incorrect highlighting when using angle brackets in a comment

### ISSUE THREAD

**Issue by MariaSolOs** [HerringtonDarkholme/yats.vim#268]
Given the following snippet of code:

```ts
enum Foo {
    A = 1 << 11, // A comment with "(" and ")"
    B = 2 << 12, // A comment with "<" and ">"
    C = 3 << 13, // A comment with "[" and "]"
}
```

This is the highlighting I obtain:
<img width="439" alt="image" src="https://github.com/HerringtonDarkholme/yats.vim/assets/62502207/58ec5f45-e532-4939-b6c0-5648ff597a1e">

If I remove the comment after `12`, then the highlighting is correct:
<img width="415" alt="image" src="https://github.com/HerringtonDarkholme/yats.vim/assets/62502207/ae11e1f3-b53a-4147-800c-b4ee4dd85613">

**Comment by HerringtonDarkholme** [comment]
It works on my branch and my configuration. Would you like to try to disable other plugins? 

![image](https://github.com/HerringtonDarkholme/yats.vim/assets/2883231/0ebcda4f-f8db-4223-b13b-0db15e64a3ae)

**Comment by MariaSolOs** [comment]
Hmmm that's strange. I'm using Neovim BTW, but I have Treesitter highlighting disabled. These are the highlight groups applied to the `12`:
<img width="324" alt="image" src="https://github.com/HerringtonDarkholme/yats.vim/assets/62502207/9ee8833f-2e6a-43e9-8579-6a1e02e185b9">

**Comment by HerringtonDarkholme** [comment]
Are you on the latest commit?

**Comment by MariaSolOs** [comment]
Okay it seems like the files that `vim` is using are outdated. I'll close the issue here.
