### ISSUE TITLE
Highlighting for the type notation in the import block is broken in syntax bundled for vim

### ISSUE THREAD

**Issue by kyoh86** [HerringtonDarkholme/yats.vim#276]
### Steps to reproduce

1. `:e foo.ts`
2. Write below code

```ts
import {
    type foo
    bar
} from "./baz";
```

3. And get invalid highlighting like this:
![image](https://github.com/vim/vim/assets/5582459/83932dbe-13b1-4a31-895a-bf5d9c72a385)

### Expected behaviour

They are highlighted like:

![image](https://github.com/vim/vim/assets/5582459/20d5a255-3468-47a8-9798-f3a7b7b285bb)

(I removed `type` and get it)

### Version of Vim

9.1.380

### Environment

Linux, x256-color, zsh

### NOTE

I reported this in vim repo, but an owner says to me to contact you.
https://github.com/vim/vim/issues/14721#issuecomment-2095313787

**Comment by rhysd** [comment]
Your code looks wrong. How about the following fixed version?

```ts
import {
    type foo,
    bar
} from "./baz";
```

**Comment by HerringtonDarkholme** [comment]
This is what I see in latest yats.vim

I think vim's upstream should be updated.

<img width="295" alt="image" src="https://github.com/HerringtonDarkholme/yats.vim/assets/2883231/c9574e94-ddb6-4a6c-8a97-c3f23f228d20">

**Comment by HerringtonDarkholme** [comment]
I think the issue should be already tracked by #277
