### ISSUE TITLE
.tsx files not highlighted

### ISSUE THREAD

**Issue by BlakeWilliams** [HerringtonDarkholme/yats.vim#28]
First of all, thanks for writing this. This is the best TypeScript syntax highlighting I could find for vim.

I saw that `.tsx` was removed here: https://github.com/HerringtonDarkholme/yats.vim/commit/ec4f3d6c8eda0ed174a02f71dbf9a44e90b03c16

Is there a reason it was removed? It's a bit of a pain to set it manually.

**Comment by davidsteinberger** [comment]
Hm, I just noticed that too. What's the reason for the removal of `.tsx`?

**Comment by HerringtonDarkholme** [comment]
Please read https://github.com/HerringtonDarkholme/yats.vim/issues/16#issuecomment-348844284

Because we really don't support tsx. You need another plugin to correctly highlight html tags in tsx.

**Comment by davidsteinberger** [comment]
Sorry, missed that. Thanks, that makes sense then!

**Comment by BlakeWilliams** [comment]
@HerringtonDarkholme That's sad to hear. It seems like TypeScript in Vim is mostly fragmented/incomplete unfortunately.

Besides JSX support this library is great, but most of the time I'm using TypeScript is with JSX.
