### ISSUE TITLE
Void type in generics reported as error

### ISSUE THREAD

**Issue by afontaine** [HerringtonDarkholme/yats.vim#3]
Void as a type on generics is accepted by TS but is highlighted as an error by YATS.

![2016-02-19 14_01_08-references d ts c__work_mmxpr_slag_webapp_app_ts - gvim](https://cloud.githubusercontent.com/assets/3373136/13185836/47a306da-d711-11e5-8301-7be321cfefc1.png)

**Comment by HerringtonDarkholme** [comment]
Thanks for report!

Fixed in https://github.com/HerringtonDarkholme/yats.vim/commit/fc8da4631c1d44cc260fdbe0c1d8cede3e075fdc

**Comment by afontaine** [comment]
Cheers!
