### ISSUE TITLE
Broken syntax highlighting

### ISSUE THREAD

**Issue by alem0lars** [HerringtonDarkholme/yats.vim#31]
![2018-01-16-093603_1044x1362_scrot](https://user-images.githubusercontent.com/336957/34979112-b49172f4-faa0-11e7-81c3-d150a4986b92.png)

**Comment by alem0lars** [comment]
More examples:

![2018-01-16-094801_1137x1003_scrot](https://user-images.githubusercontent.com/336957/34979706-62d2792a-faa2-11e7-95b5-d0fb9a0f2568.png)

**Comment by HerringtonDarkholme** [comment]
Duplicate of #5

**Comment by alem0lars** [comment]
I've updated to the latest github version and I'm still getting syntax error!

**Comment by HerringtonDarkholme** [comment]
It is closed because this issue is duplicate, not fixed.
