### ISSUE TITLE
Abstract async syntax highlight issues

### ISSUE THREAD

**Issue by alem0lars** [HerringtonDarkholme/yats.vim#35]
I've discovered that not only `abstract async` isn't highlighted properly, but also breaks the file's syntax highlighting..

![2018-01-18-080543_1118x725_scrot](https://user-images.githubusercontent.com/336957/35084911-8696764c-fc26-11e7-80eb-6e2ab56a5300.png)

**Comment by HerringtonDarkholme** [comment]
I believe this is fixed in master.
Please try it out.

**Comment by alem0lars** [comment]
I'm having the isssue after updating..

This is a screenshot of the issue:

![2018-01-18-122325_1006x878_scrot](https://user-images.githubusercontent.com/336957/35095884-7543338e-fc4a-11e7-999d-a9c8c8442085.png)

**Comment by HerringtonDarkholme** [comment]
Please paste your problem code

**Comment by alem0lars** [comment]
Here it is:

```typescript
import { IBaseProtocol } from "pg-promise";

export abstract class Model {
  abstract copy(): any;
  abstract equal(other: any): boolean;

  static areAllEqual(models: Array<Model>, others: Array<Model>) {
    if (models.length !== others.length) {
      return false;
    }

    for (let index = 0; index < models.length; index++) {
      if (!models[index].equal(others[index])) {
        return false;
      }
    }

    return true;
  }
}

export abstract class SavableModel extends Model {
  abstract async save(db: IBaseProtocol<any>): Promise<void>;
}

export abstract class CompositeTypeModel extends Model {
  constructor(readonly typeName: string) {
    super();
  }

  format(): string {
    const fields = this.formatFields();
    // TODO
    return `ROW()::${this.typeName}`;
  }

  abstract formatFields(): Array<string | undefined>;
}
```

**Comment by HerringtonDarkholme** [comment]
abstract async isn't authentic TypeScript. `abstract` method only defines a subclass' interface, not its implementation. While `async` is in effect syntax sugar for implementation. It doesn't have any impact on type level declaration.

See the [example](http://www.typescriptlang.org/play/#src=abstract%20class%20A%20%7B%0A%20%20abstract%20async%20func()%3A%20Promise%3Cvoid%3E%0A%20%20abstract%20func2()%3A%20Promise%3Cvoid%3E%0A%7D%0A%0Aclass%20B%20extends%20A%20%7B%0A%20%20async%20func2()%20%7B%20%7D%0A%20%20func()%20%7B%0A%20%20%20%20return%20Promise.resolve()%0A%20%20%7D%0A%7D)

**Comment by alem0lars** [comment]
@HerringtonDarkholme ok thanks

**Comment by HerringtonDarkholme** [comment]
I decided to remove the distinction of concrete/abstract method highlighting.
