### ISSUE TITLE
Syntax highlighting breaks for string / function / imports  if they contain a reserved keyword.

### ISSUE THREAD

**Issue by sdeprez** [HerringtonDarkholme/yats.vim#38]
Using master at time of writing (commit 8ba20cf71143376739c53f472ebeb2bfab47d9bb)

See attached screenshot:
![screenshot from 2018-01-25 16-14-02](https://user-images.githubusercontent.com/4971382/35395512-da925fa8-01ea-11e8-8c07-3f1f0a3a97d4.png)

Tested with most keywords taken from there:
https://github.com/HerringtonDarkholme/yats.vim/blob/master/syntax/basic/reserved.vim

Thanks!

**Comment by HerringtonDarkholme** [comment]
Thanks for the reporting. The first two are valid bugs.

However, function name cannot contains reserved keyword. So it is correctly highlighted.

**Comment by sdeprez** [comment]
Ok thanks for the very fast correction!
