### ISSUE TITLE
get and set function returns are highlighted as errors

### ISSUE THREAD

**Issue by afontaine** [HerringtonDarkholme/yats.vim#4]
![2016-02-26 11_35_31-amounts component ts c__work_mmxpr_slag_webapp_app_ts_remoteteller_components](https://cloud.githubusercontent.com/assets/3373136/13358394/1246e864-dc7d-11e5-92a9-4edfdd8fc58b.png)

**Comment by HerringtonDarkholme** [comment]
Thanks! fixed!
