### ISSUE TITLE
Broken syntax highlight in lambda

### ISSUE THREAD

**Issue by alem0lars** [HerringtonDarkholme/yats.vim#42]
As you can see in the picture below, line 76 breaks the syntax highlighting:

![2018-01-31-123345_1050x1111_scrot](https://user-images.githubusercontent.com/336957/35621649-69b6d206-0685-11e8-8052-af9437bd8958.png)

**Comment by alem0lars** [comment]
Probably related to issue #41 (but I'm not sure)

**Comment by HerringtonDarkholme** [comment]
Fixed with #41
