### ISSUE TITLE
Problem with template literals

### ISSUE THREAD

**Issue by agarrharr** [HerringtonDarkholme/yats.vim#47]
When I have yats installed and I use a template literal inside of jsx, I get this syntax highlighting. Everything after the template literal is blue.

<img width="441" alt="screen shot 2018-04-12 at 10 49 31 am" src="https://user-images.githubusercontent.com/3266363/38691883-57d5f994-3e3f-11e8-85ee-a34cbd8724f1.png">

Without it installed, it looks like this:

<img width="625" alt="screen shot 2018-04-12 at 10 50 54 am" src="https://user-images.githubusercontent.com/3266363/38691905-69ec2df6-3e3f-11e8-80ca-57ca5acf05d9.png">

**Comment by HerringtonDarkholme** [comment]
The problem is that yats hasn't JSX support yet. I plan to add it but I'm busy with other stuff IRL.

FYI, JSX support is tracked in #36
