### ISSUE TITLE
tsxRegion

### ISSUE THREAD

**Issue by Arelav** [HerringtonDarkholme/yats.vim#48]
Can you add please tsxRegion support? Like in https://github.com/ianks/vim-tsx/blob/master/after/syntax/tsx.vim

I'll be very happy to use YATS instead other TS/TSX syntax highlighting plugins.

It's useful together with [vim-context-commentstring](vim-context-commentstring) because the comments is tsx file is defferent for ts and tsx synta

**Comment by Arelav** [comment]
Great! Thanks. I hope we will see this soon.

**Comment by HerringtonDarkholme** [comment]
I have pushed some initial work on JSX.

It is still in progress, so some feature might not work.
