### ISSUE TITLE
typescriptreact broken on all class-based jsx componenents

### ISSUE THREAD

**Issue by dsifford** [HerringtonDarkholme/yats.vim#49]
Hi there,

Loving the new jsx support. Great work.

One issue I've ran into is that in files that have component trees rendered within jsx fragments, the syntax for the entire tree breaks.

**Edit:** See comment below

**Comment by dsifford** [comment]
**Update:** It's not fragment syntax. It looks like any component that is created as a class is broken.

**Broken:**
```tsx
export class Foo extends React.Component {
    render() {
        return <div>asdf</div>
    }
}
```

**Comment by HerringtonDarkholme** [comment]
Thanks for report!

**Comment by HerringtonDarkholme** [comment]
I found jsx fragment is still broken.

**Comment by dsifford** [comment]
Also, while I'm on that topic, I think it would be beneficial to split the `jsxTagName` group into two separate groups for built-in tags and custom component tags.

Textmate does this simply by targeting the first letter of the tag... If it's a uppercase, then it's scoped to `class`, if it's lowercase it's scoped to `htmlTag`.

**Comment by HerringtonDarkholme** [comment]
Thanks for the suggestion! I will try that!
