### ISSUE TITLE
Please remove the setting of formatoptions from the ftplugin

### ISSUE THREAD

**Issue by dsifford** [HerringtonDarkholme/yats.vim#50]
Hello again,

I personally do not like it when `o` or `O` prepends comments. Setting this as you do in the ftplugin overrides my personal settings. 

This doesn't seem specific to the syntax. IMHO, it shouldn't be messed with.

Thanks for considering.

https://github.com/HerringtonDarkholme/yats.vim/blob/c7d7f9670627323020dca931e6984d51391dc27a/ftplugin/typescript.vim#L16

**Comment by HerringtonDarkholme** [comment]
Could you tell me any reason that you cannot override the option in your vimrc?

It should be doable IIRC.

**Comment by dsifford** [comment]
I currently have it set in my vimrc, but it's static so any time I change to a ts or tsx file it'll get overwritten.

I could override the changes by adding it again inside a ftplugin, but I really don't want to because repeating code is annoying and also I don't believe this is something that an external syntax plugin should be messing with becuase it has nothing to do with syntax.

**Comment by dsifford** [comment]
I just ended up adding the autocommand to fix this.

Closing since my issue is technically fixed (though I still don't think this plugin should mess with that stuff)

Thanks anyways @HerringtonDarkholme
