### ISSUE TITLE
Syntax highlight breaks for inner keys whose value is another object with a function in one of its child values.

### ISSUE THREAD

**Issue by sdeprez** [HerringtonDarkholme/yats.vim#53]
Using master at time of writing: (commit e2b862a57d52e2cd5bf68e37e934058d4b74192e).

See screenshot for the object that broke the highlighting:
![screenshot from 2018-05-22 18-20-00](https://user-images.githubusercontent.com/4971382/40375746-c16095be-5dec-11e8-8f96-4b2610374b17.png)

Thanks!

**Comment by HerringtonDarkholme** [comment]
I cannot support the feature.

`var b = ({ inner: (a) => 123 })` is ambiguous with other language feature.

**Comment by sdeprez** [comment]
Thanks for your answer. Is it ambiguous though? Do you see another way of parsing it rather, declare an `object` with a key `inner` whose value is a function, and wrap the object in parenthesis (which is not needed in your example when you assign it to `b`, but required if you put that object into another one, like in my example).

**Comment by sdeprez** [comment]
Alright, you meant ambiguous for VimScript! Well unfortunately I don't know much about it so I cannot suggest any workaround. If you could somehow find one that'd be awesome, in the meantime I'll leave it up to you what to do with issue!
