### ISSUE TITLE
Found a couple missing type syntax tokens

### ISSUE THREAD

**Issue by dsifford** [HerringtonDarkholme/yats.vim#54]
Hello again,

I found a few missing syntax definitions when editing a `.d.ts` file this afternoon.

Here's an example:

```ts
declare namespace Outer {
    namespace Inner {
  //^^^^^^^^^ no syntax group
        // [...]
    }
    type Thing = 'foo' | 'bar' | 'baz';
  //^^^^ no syntax group
}
```

Thanks again. Great work on the JSX additions!

**Comment by dsifford** [comment]
Oh, forgot one more..

Consider this situation...

```ts
type Thing = 'foo' | 'bar' | 'baz';
               //  ^       ^  both of these scoped correctly
```

This breaks if it is formatted this way (which is valid syntax)

```ts
type Thing = 
           | 'foo'
           | 'bar'
           | 'baz';
```

Thanks again!

**Comment by dsifford** [comment]
No rush. I appreciate you :smile:

**Comment by HerringtonDarkholme** [comment]
Fixed in master!
