### ISSUE TITLE
Breaks when interface has braces on new line

### ISSUE THREAD

**Issue by kontheocharis** [HerringtonDarkholme/yats.vim#56]
I seem to have stumbled upon a bug where if there is an interface declaration and the curly brace is on a new line, nothing inside the interface gets highlighted.

![rec](https://user-images.githubusercontent.com/18248100/40747460-a7e35ec4-645d-11e8-8af0-aae7eedca662.gif)

By the way, very nice plugin!

**Comment by HerringtonDarkholme** [comment]
Thanks for report. 

I will look at them when I'm available.
