### ISSUE TITLE
Some syntax not recognised in Angular projects

### ISSUE THREAD

**Issue by pavilion** [HerringtonDarkholme/yats.vim#57]
![image](https://user-images.githubusercontent.com/3165436/40874546-9a92f20e-6668-11e8-9ca4-7f2ed891fe78.png)
Notice that some syntax is not recognised as:
`ActivatedRoute` and `HeroesService` are not recognised as classes/interfaces
`subscribe` method is not recognised as a method
`params` is not recognised as well

This is how it would look in VSCode
![image](https://user-images.githubusercontent.com/3165436/40874629-551e0c9e-6669-11e8-9eb5-4d17540dbfee.png)

**Comment by HerringtonDarkholme** [comment]
This is what I see.

![screenshot from 2018-06-03 15-37-57](https://user-images.githubusercontent.com/2883231/40884329-21ab6538-6744-11e8-94d3-3fe0659d314e.png)

It looks like function parameter is correctly highlighted.

I don't want to support different highlighting for method and class name. They are usually slow.

**Comment by pavilion** [comment]
I tested if it was the theme so I changed to Solarized and NeoSolarized. It does not change anything. Do you know what it could be?

**Comment by HerringtonDarkholme** [comment]
Can you paste a screenshot of Solarized?

Also https://gist.github.com/mattsacks/1544768 

Could you use this gist and report your synstack under cursor?

**Comment by pavilion** [comment]
![image](https://user-images.githubusercontent.com/3165436/41038260-8029d0d6-698d-11e8-8f88-a0cc28c3ea97.png)

Synstack report:
cursor under `_activatedRoute` prompts => `foldBraces`
`ActivateRoute` => `foldBraces`
`params` => `foldBraces` (*twice*)
`selector` => `foldBraces`
`templateURL` => `foldBraces`
`private` => `foldBraces` + `typescriptReserved`
`@Component` => `typescriptDecorators`

**Comment by HerringtonDarkholme** [comment]
Can you paste the code?

My synstack for selector is 

```
typescriptParenExp->typescriptObjectLiteral->typescriptObjectLabel  HltTrace: typescriptObjectLab
el->typescriptLabel->Label->Statement
```

**Comment by HerringtonDarkholme** [comment]
This plugin is very useful https://github.com/gerw/vim-HiLinkTrace

**Comment by pavilion** [comment]
@HerringtonDarkholme I am not used to these kind of plugins... May I ask what should I do? If I select all the code and run :Syn I get "E481: No range allowed"

**Comment by pavilion** [comment]
`import { Component } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { HeroesService } from '../services/heroes.service';
@Component({
  selector: 'app-heroe',
  templateUrl: './heroe.component.html'
})
export class HeroeComponent {

  heroe: any = {
  };

  constructor(private _activatedRoute: ActivatedRoute, private _heroesService: HeroesService) {
    this._activatedRoute.params.subscribe(params => {
      this.heroe = this._heroesService.getHeroe(params['id']);
    });

  }

}`

That's the code

**Comment by HerringtonDarkholme** [comment]
![screen shot 2018-06-07 at 10 15 33 am](https://user-images.githubusercontent.com/2883231/41074665-be251c0c-6a3b-11e8-84df-f80e9b1a85eb.png)


I cannot reproduce.

Please minimize your vimrc and provide a valid reproduction.

**Comment by pavilion** [comment]
This is what I get for selector:
`SynStack:  foldBraces                          HltTrace: T:foldBraces->                      fg<> bg<> `

I've tried to debug my virmc file and apparently, it seems like all plugins don't interfere with the encoding or mapping.

**Comment by HerringtonDarkholme** [comment]
> t seems like all plugins don't interfere with yats plugin,

Please paste your minimized vimrc and Vim version.

**Comment by pavilion** [comment]
Sure, what should I include in that minimized vimrc?
Btw, here is a [gist](https://gist.github.com/pavilion/98937764577a6dc08ab390fcfe2f5dee) containing what happens from the time I open `heroe.component.ts`

**Comment by pavilion** [comment]
FOUND IT!
removed
https://github.com/sheerun/vim-polyglot 
and not it's working fine!
