### ISSUE TITLE
*Some* private, new, static, and public reported as error

### ISSUE THREAD

**Issue by indiesquidge** [HerringtonDarkholme/yats.vim#6]
![screen shot 2016-03-01 at 4 34 45 pm](https://cloud.githubusercontent.com/assets/3409645/13446892/fb514a76-dfcb-11e5-9b0f-1362348661a4.png)

**Comment by HerringtonDarkholme** [comment]
Thanks for reporting! It's a known bug. But I found it very hard to fix.

**Comment by HerringtonDarkholme** [comment]
Hi, I have tried to fix it in ab251cb1c033e8e0045bbee7797f4be328923f43

**Comment by indiesquidge** [comment]
@HerringtonDarkholme I'm still getting the same error highlighting :(

Interestingly, if I put the `private $$popoverInits` property all on one line, the highlighting appears as it should.
<img width="1043" alt="screen shot 2016-03-02 at 9 57 01 am" src="https://cloud.githubusercontent.com/assets/3409645/13469642/2743e788-e05d-11e5-9d93-312269b45ce7.png">

So is this perhaps a line length setting that needs to be configured for highlighting in `yats`?

**Comment by HerringtonDarkholme** [comment]
You have to put them in one line when you both have type annotation and variable initialization.

https://github.com/HerringtonDarkholme/yats.vim/blob/master/syntax/basic/class.vim#L58-L61

But I think it might be fixable.

**Comment by HerringtonDarkholme** [comment]
@indiesquidge  Can you try 92c5edd7e0edff41ab95b1dfcf618949a2e49a3d? It might be fixed.

**Comment by indiesquidge** [comment]
@HerringtonDarkholme that did it! Thank you so much, I appreciate your quick responses and help on getting this fixed :)

**Comment by indiesquidge** [comment]
@HerringtonDarkholme bad news, there are still cases when the syntax gets all wacky :(
<img width="907" alt="screen shot 2016-03-03 at 9 14 13 pm" src="https://cloud.githubusercontent.com/assets/3409645/13518629/efc5c4e2-e184-11e5-96c9-255d30b9f416.png">

**Comment by indiesquidge** [comment]
Here's another

<img width="731" alt="screen shot 2016-03-03 at 9 53 22 pm" src="https://cloud.githubusercontent.com/assets/3409645/13519226/6aea1f9c-e18a-11e5-803e-de1ad592b2af.png">

I can fix it by not using an implicit return

<img width="731" alt="screen shot 2016-03-03 at 9 56 55 pm" src="https://cloud.githubusercontent.com/assets/3409645/13519274/e1e89a1a-e18a-11e5-8899-f2acd1fa72eb.png">

But implicit returns are a pretty core feature of arrow functions in both `ES6` and TypeScript, so it seems fitting for us to get it fixed.

```javascript
(param1, param2, …, paramN) => { statements }
(param1, param2, …, paramN) => expression
         // equivalent to:  => { return expression; }

// Parentheses are optional when there's only one parameter:
(singleParam) => { statements }
singleParam => { statements }

// A function with no parameters requires parentheses or an underscore:
() => { statements }
_ => { statements }
```

**Comment by HerringtonDarkholme** [comment]
The second example is hard to fix. As pointed out in https://github.com/HerringtonDarkholme/yats.vim/issues/5

You can bypass the first situation by `new Map<string, EvoDropDownControl>()`

Vim's syntax highlighting is not powerful enough to describe all language construct (not only TS, but also other languages.)
I don't expect yats can be 100% correct, but it can cover a lot of common usage.

**Comment by indiesquidge** [comment]
Looks like [typescript-vim](https://github.com/leafgarland/typescript-vim) implements it.

<img width="731" alt="screen shot 2016-03-03 at 11 02 05 pm" src="https://cloud.githubusercontent.com/assets/3409645/13520290/ff752b44-e193-11e5-8037-eb4fe9b17850.png">

Perhaps we can find a way to take their implementation. I will do some digging.

**Comment by HerringtonDarkholme** [comment]
No it does not.
typescript-vim just skips some highlight semantic. So it make less error too.

For example, typescript-vim does not highlight argument type annotation. I also suspect it just highlight `private` keyword in more broad situation(say, in a method block, in non class block).

yats' highlight is richer, so it is more error-prone. I'm wondering if this is a good approach, especially in vimscript.

**Comment by HerringtonDarkholme** [comment]
Or the simplest way to fix all `error highlight` is just removing those error detection highlighting. After all, typescript needs to be compiled.

**Comment by indiesquidge** [comment]
You are correct that `typescript-vim` picks up on keywords and methods, but not on argument types (i.e. the highlighting is based on words themselves rather than their context). I prefer your plugin more since it does offer a wider, more colorful range of highlighting. However, `typescript-vim` doesn't show error highlighting where it shouldn't , and I haven't come across a case where they syntax will blow up on a line error.

I think there is a balance between how "rich" a syntax highlighting plugin is and how it is able to handle the plethora of corner cases without messing subsequent lines.
