### ISSUE TITLE
Wrong highlight for -> export default interface

### ISSUE THREAD

**Issue by Saul-Mirone** [HerringtonDarkholme/yats.vim#60]
![image](https://user-images.githubusercontent.com/10047788/41755112-327cfbe2-7608-11e8-9add-4b45361ff929.png)

![image](https://user-images.githubusercontent.com/10047788/41755126-3e501ad0-7608-11e8-887d-d03de1baf5da.png)

**Comment by HerringtonDarkholme** [comment]
Fixed in 6d3bb82
