### ISSUE TITLE
Treat object method and object props differently

### ISSUE THREAD

**Issue by aakashsigdel** [HerringtonDarkholme/yats.vim#61]
Sorry if this is completely wrong place to ask this. If it is, I am happy to move this issue elsewhere.

I use grubbox theme on both vscode and vim. I am using YATS to for highlight. But on vim the colors look kind of different.

For example the object properties are treated differently than object methods on vscode but not on yats.

As you can see from the screenshot below. The getters are different also, object properties and object methods are different.

I have tried multiple themes with similar result

Is it possible to highlight object properties and object methods differently. Also is there a way to highlight getters ('get' keyword) differently?

VSCode
--
<img width="664" alt="screen shot 2018-07-06 at 4 34 16 pm" src="https://user-images.githubusercontent.com/4772643/42384336-fcf92e68-8139-11e8-819b-d0770752fb70.png">

Vim
--
<img width="665" alt="screen shot 2018-07-06 at 4 35 59 pm" src="https://user-images.githubusercontent.com/4772643/42384340-ff0adeea-8139-11e8-8f8b-49df60eb9157.png">

**Comment by HerringtonDarkholme** [comment]
I have added this feature before but removed later because it's too slow in vim.

So I can't support it.
