### ISSUE TITLE
Template string highlight is incorrect when using a tagged templates

### ISSUE THREAD

**Issue by djwelch** [HerringtonDarkholme/yats.vim#63]
Hi,

If I use a template string tagged template such as:
```
const processed = { data: T`${"hello"} my name is ${"something"}`, };
function T(literals: TemplateStringsArray, ...placeholders: any[]) {
  return {literals, placeholders};
}
```

Then the plugin just highlights as text from the first back tick all the way down.

Screenshot:
![image](https://user-images.githubusercontent.com/1104278/42732294-c39dbe2a-8816-11e8-91f7-caf81e3e01f4.png)

without the `T` then it looks like:
![image](https://user-images.githubusercontent.com/1104278/42732299-e90ec262-8816-11e8-91a6-3863a6ea12e4.png)
which is correct.

**Comment by HerringtonDarkholme** [comment]
This should be fixed now!
