### ISSUE TITLE
Reference paths not treated with comment syntax

### ISSUE THREAD

**Issue by indiesquidge** [HerringtonDarkholme/yats.vim#7]
![screen shot 2016-03-01 at 4 39 26 pm](https://cloud.githubusercontent.com/assets/3409645/13446923/373af2e4-dfcc-11e5-847a-076932b0e7e9.png)

**Comment by HerringtonDarkholme** [comment]
Hi @indiesquidge, this is an intended feature. Reference paths are not merely comment in TypeScript. I want to highlight them.

**Comment by indiesquidge** [comment]
Ah, I see. Makes sense :)
