### ISSUE TITLE
semicolon highlighting

### ISSUE THREAD

**Issue by mikekreeki** [HerringtonDarkholme/yats.vim#73]
Would it be possible to add highlight group for semicolons? 🙏 

Thanks, appreciated!

**Comment by tomaskallup** [comment]
Turns out there actually is one, but it's not being properly highlighted, I'll get on it

**Comment by tomaskallup** [comment]
In #80 I've fixed the group, but that one is only inteded for typescript interface/type definition and as was said in #76, this might not get accepted. If you really want this, you could add your own group in your vim configuration.

**Comment by HerringtonDarkholme** [comment]
Thank @tomaskallup for fixing multiple issues!

As said before, semicolons aren't significant syntax components. We won't add it to highlight group by default but `typescriptEndColon` is available for your own configuration.
