### ISSUE TITLE
Some magic comments aren't highlighted.

### ISSUE THREAD

**Issue by afontaine** [HerringtonDarkholme/yats.vim#8]
amd-dependency, used to ensure the dependency is added when compiled, isn't highlighted.

![image](https://cloud.githubusercontent.com/assets/3373136/13672292/2c988414-e6a2-11e5-8b8c-77a24b8e3f58.png)

**Comment by HerringtonDarkholme** [comment]
I didn't see this magic comment in spec.
https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md

**Comment by afontaine** [comment]
Odd. It's been in the language since before 1.5 https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#amd-dependency-optional-names

There's also amd-module, from 1.4 https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#amd-module-names

**Comment by HerringtonDarkholme** [comment]
Added in da6dc5f2a926529f3d030906c6335d6526775656
