### ISSUE TITLE
Some highlight groups are not working

### ISSUE THREAD

**Issue by cseelus** [HerringtonDarkholme/yats.vim#88]
Tried different VIM color schemes and also tried to change colors for these highlight groups manually, but they just keep the color of the `Normal` highlight group:

`typescriptIdentifierName`
~`typescriptParens`~
~`typescriptParenExp`~
`typescriptProp`

I'm using Neovim 0.3.1 on macOS 10.14.

**Comment by tomaskallup** [comment]
That seems weird, I tried to run `hi link typescriptParens special` and everything works as expected. These are just regular syntax groups, I don't see why this would not work. Could you try this on a clean config with only yats, to see if maybe there is some other plugin causing it?

**Comment by cseelus** [comment]
Thanks for the quick reply. Does `hi link typescriptIdentifierName special` or `hi link typescriptProp special` work for you also?

For example with

```typescript
const styles = StyleSheet.create({
  // some styles
});
```

… `.create` is a `typescriptProp` syntax group and can't be colored.

**Comment by HerringtonDarkholme** [comment]
@cseelus @tomaskallup This is because typescriptIdentifierName and typescriptProp are transparent group. They are designed to reflect their surrounding syntax group. e.g. `(identifier) => 123` identifier is highlighted as typescriptIdentifierName, but displayed as `Special` because it is surrounded by typescriptArg

**Comment by cseelus** [comment]
Thanks for the explanation, makes sense.

Any chance imports from a module could get their own highlight instead of `typescriptIdentifierName`, for example `typescriptModuleKeyword`, so VIM colorschemes could accentuate them better? Currently they are just displayed like `Normal` text.
