### ISSUE TITLE
Default typed arguments results in crash/slowness

### ISSUE THREAD

**Issue by karthikiyengar** [HerringtonDarkholme/yats.vim#89]
Minimal reproduction, try typing
```typescript
>export default (state: Car = "Ferrari",
```

**Comment by HerringtonDarkholme** [comment]
Are you using vim or neovim?

Neovim is a lot faster in highlighting and the test case above seems to work fine.

**Comment by karthikiyengar** [comment]
I was using MacVim/standard before.

Works flawlessly on `nvim` - Thanks :-)

**Comment by HerringtonDarkholme** [comment]
Hmm, I think I will recommend users to adopt neovim.
