### ISSUE TITLE
class member property and method should have different scopes

### ISSUE THREAD

**Issue by uloco** [HerringtonDarkholme/yats.vim#93]
The definition of class properties and methods should have different scopes, so that they can be highlighted with different colors. The usual way is to colorize the method like a function definition. At the moment all class members are colored the same, because they have the scope `typescriptMember`. Even when calling the methods they have both the scope `typescriptProp`.

![screenshot 2019-01-18 at 11 40 17](https://user-images.githubusercontent.com/8818340/51382002-ef9fc800-1b15-11e9-8642-f824bd23d057.png)

Is there any way of implementing this behaviour? It really irritates me, and keeps me away from working with typescript in neovim ... :/

**Comment by HerringtonDarkholme** [comment]
I deliberately chose to not differentiate properties and methods. The reason is performance: telling a property from a method requires lookahead and backtracking which slow down vim.
