### ISSUE TITLE
General types are underlined

### ISSUE THREAD

**Issue by daniel-hoffmann** [HerringtonDarkholme/yats.vim#95]
Using neovim 0.3.4 (with all plugins except for yats disabled) I get the following display:

![screen shot 2019-02-08 at 15 45 23](https://user-images.githubusercontent.com/4301259/52489931-7565df00-2bbb-11e9-9c5e-1c5b39603eb0.png)

When I change the type to Boolean the underline goes away.  As per 

https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html

The capitalized version should not be used? So maybe this is just the wrong way round? Or am I doing something wrong here?

**Comment by HerringtonDarkholme** [comment]
It is a problem of syntax linking. Note that `PredefinedType` is linked to `Underlined`.  So I think you can change the syntax highlight group will solve this problem.
