### ISSUE TITLE
YATS seems to crash neovim on certain file

### ISSUE THREAD

**Issue by green-arrow** [HerringtonDarkholme/yats.vim#99]
nvim: 0.3.4

When opening a file with the following contents, my entire nvim hangs up and becomes unresponsive. I have to manually run `killall nvim` and restart. Disabling yats fixes the problem. I'm using `leafgarland/typescript-vim` currently, but I would prefer to use this syntax plugin.

Please let me know if you need any more information.

```ts
import { applyMiddleware, createStore } from 'redux';
import thunk from 'redux-thunk';
import { composeWithDevTools } from 'redux-devtools-extension/logOnlyInProduction';
import sentry from './middlewares/sentry';
import { reducer as accountReducer } from './modules/account';
import { reducer as apiReducer } from './modules/api';
import makeRootReducer from './reducers';
import APP_CONFIG from '../config';

export default (initialState = {}) => {
  const reducer = makeRootReducer({
    account: accountReducer,
    api: apiReducer,
  });
  const middlewares = applyMiddleware(
    sentry(),
    thunk.withExtraArgument(APP_CONFIG)
  );
  const enhancer = composeWithDevTools(middlewares);

  // ======================================================
  // Store Instantiation
  // ======================================================
  const store = createStore(reducer, initialState, enhancer);

  return store;
};
```

**Comment by HerringtonDarkholme** [comment]
I don't think this is yats's fault. I didn't manage to reproduce it on my machine. (OSX, nvim 0.34).

I suggest you disable all other plugins and if problem still exists please report it to neovim's repo.

**Comment by sandangel** [comment]
@HerringtonDarkholme I got the same issue. I disabled all the plugins except yast.vim, but neovim still crash when I open a certain ts file.

**Comment by hojberg** [comment]
I have also been seeing these issues.

**Comment by hojberg** [comment]
I figured this out. `re=1` will cause this. Remove that line if you have it in your vimrc.
